//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCareService.HealthService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HealthService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShiPian_Login", ReplyAction="http://tempuri.org/IService1/ShiPian_LoginResponse")]
        System.Data.DataSet ShiPian_Login(string strUsername, string strPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShiPian_Login", ReplyAction="http://tempuri.org/IService1/ShiPian_LoginResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ShiPian_LoginAsync(string strUsername, string strPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Hall_Login", ReplyAction="http://tempuri.org/IService1/Hall_LoginResponse")]
        System.Data.DataSet Hall_Login(string strUsername, string strPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Hall_Login", ReplyAction="http://tempuri.org/IService1/Hall_LoginResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Hall_LoginAsync(string strUsername, string strPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Get_Richeng", ReplyAction="http://tempuri.org/IService1/Get_RichengResponse")]
        System.Data.DataSet Get_Richeng(string id, string userid, string Togeter_date, string Session_id, string Togeter_hall, string is_upload, string realName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Get_Richeng", ReplyAction="http://tempuri.org/IService1/Get_RichengResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_RichengAsync(string id, string userid, string Togeter_date, string Session_id, string Togeter_hall, string is_upload, string realName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Get_TableInfo", ReplyAction="http://tempuri.org/IService1/Get_TableInfoResponse")]
        System.Data.DataSet Get_TableInfo(string strSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Get_TableInfo", ReplyAction="http://tempuri.org/IService1/Get_TableInfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_TableInfoAsync(string strSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExecuteNonQuery", ReplyAction="http://tempuri.org/IService1/ExecuteNonQueryResponse")]
        bool ExecuteNonQuery(string strSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExecuteNonQuery", ReplyAction="http://tempuri.org/IService1/ExecuteNonQueryResponse")]
        System.Threading.Tasks.Task<bool> ExecuteNonQueryAsync(string strSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Get_Togeter_hall", ReplyAction="http://tempuri.org/IService1/Get_Togeter_hallResponse")]
        System.Data.DataSet Get_Togeter_hall();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Get_Togeter_hall", ReplyAction="http://tempuri.org/IService1/Get_Togeter_hallResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Togeter_hallAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Get_Togeter_date", ReplyAction="http://tempuri.org/IService1/Get_Togeter_dateResponse")]
        System.Data.DataSet Get_Togeter_date();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Get_Togeter_date", ReplyAction="http://tempuri.org/IService1/Get_Togeter_dateResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Togeter_dateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelProgram", ReplyAction="http://tempuri.org/IService1/DelProgramResponse")]
        bool DelProgram(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelProgram", ReplyAction="http://tempuri.org/IService1/DelProgramResponse")]
        System.Threading.Tasks.Task<bool> DelProgramAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Update_Richeng", ReplyAction="http://tempuri.org/IService1/Update_RichengResponse")]
        bool Update_Richeng(string ID, string title, string userid, string Togeter_date, string Session_id, string Togeter_hall, string time_slot, string realName, string is_upload, string is_upload_en, string filedir, string have_video, string org, string AuthorizeState, string mobile_phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Update_Richeng", ReplyAction="http://tempuri.org/IService1/Update_RichengResponse")]
        System.Threading.Tasks.Task<bool> Update_RichengAsync(string ID, string title, string userid, string Togeter_date, string Session_id, string Togeter_hall, string time_slot, string realName, string is_upload, string is_upload_en, string filedir, string have_video, string org, string AuthorizeState, string mobile_phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Add_Richeng", ReplyAction="http://tempuri.org/IService1/Add_RichengResponse")]
        bool Add_Richeng(string title, string userid, string Togeter_date, string Session_id, string Togeter_hall, string time_slot, string realName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Add_Richeng", ReplyAction="http://tempuri.org/IService1/Add_RichengResponse")]
        System.Threading.Tasks.Task<bool> Add_RichengAsync(string title, string userid, string Togeter_date, string Session_id, string Togeter_hall, string time_slot, string realName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : HealthCareService.HealthService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<HealthCareService.HealthService.IService1>, HealthCareService.HealthService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ShiPian_Login(string strUsername, string strPass) {
            return base.Channel.ShiPian_Login(strUsername, strPass);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ShiPian_LoginAsync(string strUsername, string strPass) {
            return base.Channel.ShiPian_LoginAsync(strUsername, strPass);
        }
        
        public System.Data.DataSet Hall_Login(string strUsername, string strPass) {
            return base.Channel.Hall_Login(strUsername, strPass);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Hall_LoginAsync(string strUsername, string strPass) {
            return base.Channel.Hall_LoginAsync(strUsername, strPass);
        }
        
        public System.Data.DataSet Get_Richeng(string id, string userid, string Togeter_date, string Session_id, string Togeter_hall, string is_upload, string realName) {
            return base.Channel.Get_Richeng(id, userid, Togeter_date, Session_id, Togeter_hall, is_upload, realName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_RichengAsync(string id, string userid, string Togeter_date, string Session_id, string Togeter_hall, string is_upload, string realName) {
            return base.Channel.Get_RichengAsync(id, userid, Togeter_date, Session_id, Togeter_hall, is_upload, realName);
        }
        
        public System.Data.DataSet Get_TableInfo(string strSql) {
            return base.Channel.Get_TableInfo(strSql);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_TableInfoAsync(string strSql) {
            return base.Channel.Get_TableInfoAsync(strSql);
        }
        
        public bool ExecuteNonQuery(string strSql) {
            return base.Channel.ExecuteNonQuery(strSql);
        }
        
        public System.Threading.Tasks.Task<bool> ExecuteNonQueryAsync(string strSql) {
            return base.Channel.ExecuteNonQueryAsync(strSql);
        }
        
        public System.Data.DataSet Get_Togeter_hall() {
            return base.Channel.Get_Togeter_hall();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Togeter_hallAsync() {
            return base.Channel.Get_Togeter_hallAsync();
        }
        
        public System.Data.DataSet Get_Togeter_date() {
            return base.Channel.Get_Togeter_date();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Togeter_dateAsync() {
            return base.Channel.Get_Togeter_dateAsync();
        }
        
        public bool DelProgram(string id) {
            return base.Channel.DelProgram(id);
        }
        
        public System.Threading.Tasks.Task<bool> DelProgramAsync(string id) {
            return base.Channel.DelProgramAsync(id);
        }
        
        public bool Update_Richeng(string ID, string title, string userid, string Togeter_date, string Session_id, string Togeter_hall, string time_slot, string realName, string is_upload, string is_upload_en, string filedir, string have_video, string org, string AuthorizeState, string mobile_phone) {
            return base.Channel.Update_Richeng(ID, title, userid, Togeter_date, Session_id, Togeter_hall, time_slot, realName, is_upload, is_upload_en, filedir, have_video, org, AuthorizeState, mobile_phone);
        }
        
        public System.Threading.Tasks.Task<bool> Update_RichengAsync(string ID, string title, string userid, string Togeter_date, string Session_id, string Togeter_hall, string time_slot, string realName, string is_upload, string is_upload_en, string filedir, string have_video, string org, string AuthorizeState, string mobile_phone) {
            return base.Channel.Update_RichengAsync(ID, title, userid, Togeter_date, Session_id, Togeter_hall, time_slot, realName, is_upload, is_upload_en, filedir, have_video, org, AuthorizeState, mobile_phone);
        }
        
        public bool Add_Richeng(string title, string userid, string Togeter_date, string Session_id, string Togeter_hall, string time_slot, string realName) {
            return base.Channel.Add_Richeng(title, userid, Togeter_date, Session_id, Togeter_hall, time_slot, realName);
        }
        
        public System.Threading.Tasks.Task<bool> Add_RichengAsync(string title, string userid, string Togeter_date, string Session_id, string Togeter_hall, string time_slot, string realName) {
            return base.Channel.Add_RichengAsync(title, userid, Togeter_date, Session_id, Togeter_hall, time_slot, realName);
        }
    }
}
